Vagrant.configure("2") do |config|
    config.vm.define "serverS" do |s|
        s.vm.box = "centos/7"
        s.vm.hostname = "serverS"
        s.vm.network "private_network", ip: "192.168.42.110"
        s.vm.provider "virtualbox" do |v|
            v.name = "serverS"
            v.memory = 1024
            v.cpus = 1
        end
        s.vm.provision "shell", inline: <<-SHELL
        yum install -y net-tools
        export K3S_KUBECONFIG_MODE="644"
		export INSTALL_K3S_EXEC="--flannel-iface eth1"
		curl -sfL https://get.k3s.io | sh -
        /usr/local/bin/kubectl apply -f /vagrant/manifest/app_one.yaml
        /usr/local/bin/kubectl apply -f /vagrant/manifest/app_two.yaml
        /usr/local/bin/kubectl apply -f /vagrant/manifest/app_three.yaml        
        /usr/local/bin/kubectl apply -f /vagrant/ingress.yaml
        SHELL
    end
end